[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.exif"
]

[phases.build]
cmds = [
  "composer update --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
